Unidad 3
Practica 3: KNN en Prestamos Lending Club



In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
# Importamos librerias necesarias para knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve

In [ ]:
prestamos_df = pd.read_csv('prestamos_ok.csv')
prestamos_df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens,hardship_flag,disbursement_method,debt_settlement_flag,debt_settlement_flag_date
0,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
1,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
2,3000,3000,3000.0,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
3,5600,5600,5600.0,60 months,21.28,152.39,F,F2,NaN,4 years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
4,5375,5375,5350.0,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN


In [ ]:
X = prestamos_df[['funded_amnt', "int_rate", "grade", 'purpose', 'addr_state',
'home_ownership', 'annual_inc', 'dti', 'revol_util',
'pub_rec_bankruptcies']]
# Variable objetivo o variable a predecir
y = prestamos_df["loan_status"]

In [ ]:
import pandas as pd

# Identificamos las columnas categóricas que necesitan codificación one-hot
categorical_cols = ['grade', 'purpose', 'addr_state', 'home_ownership']

# Aplicamos one-hot encoding a estas columnas en el DataFrame X
# drop_first=True evita la multicolinealidad y reduce el número de columnas
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

# Mostramos las primeras filas del DataFrame X transformado para verificar
display(X.head())

,funded_amnt,int_rate,annual_inc,dti,revol_util,pub_rec_bankruptcies,grade_B,grade_C,grade_D,grade_E,...,purpose_wedding,addr_state_FL,addr_state_IL,addr_state_NJ,addr_state_NY,addr_state_TX,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT
0,2400,15.96,12252.0,8.72,98.5,0.0,False,True,False,False,...,False,False,True,False,False,False,False,False,False,True
1,10000,13.49,49200.0,20.00,21.0,0.0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
2,3000,18.64,48000.0,5.35,87.5,0.0,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
3,5600,21.28,40000.0,5.55,32.6,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,5375,12.69,15000.0,18.08,36.5,0.0,True,False,False,False,...,False,False,False,False,False,True,False,False,False,True


In [ ]:
# Dividimos el dataFrame en X_train y X_test.
# 60% para dataset de entrenamiento, y 40% para dataset de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [ ]:
# Eliminar filas con valores nulos en X_train y X_test
X_train = X_train.dropna()
y_train = y_train.loc[X_train.index] # Asegurarse de que y_train coincide con las filas restantes de X_train

X_test = X_test.dropna()
y_test = y_test.loc[X_test.index] # Asegurarse de que y_test coincide con las filas restantes de X_test

print(f'Shape of X_train after dropping NaNs: {X_train.shape}')
print(f'Shape of X_test after dropping NaNs: {X_test.shape}')

Shape of X_train after dropping NaNs: (11744, 34)
Shape of X_test after dropping NaNs: (7832, 34)


In [ ]:
# verificamos la cantidad de registros asignados al dataframe de entrenamiento
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((11944, 34), (7964, 34), (11944,), (7964,))

In [ ]:
# Creamoos el clasificador de regresion logistica
knn1 = KNeighborsClassifier(n_neighbors = 1)
# Entrenamos el clasificador
knn1.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn1.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 1.0


In [ ]:
# Realizar una prediccion con los datos de prueba
y_pred = knn1.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 1 vecino: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz Confusion con 1 vecino:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 1 vecino: 
               precision    recall  f1-score   support

   No Pagado       0.16      0.15      0.16      1190
      Pagado       0.85      0.87      0.86      6642

    accuracy                           0.76      7832
   macro avg       0.51      0.51      0.51      7832
weighted avg       0.75      0.76      0.75      7832


Matriz Confusion con 1 vecino:
 [[ 176 1014]
 [ 892 5750]]


In [ ]:
# Creamoos el clasificador de regresion logistica
knn5 = KNeighborsClassifier(n_neighbors = 5)
# Entrenamos el clasificador
knn5.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn5.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 0.8633344686648501


In [ ]:
# Realizar una prediccion con los datos de prueba
y_pred = knn5.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 5 vecinos: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 5 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.20      0.03      0.06      1190
      Pagado       0.85      0.98      0.91      6642

    accuracy                           0.83      7832
   macro avg       0.53      0.50      0.48      7832
weighted avg       0.75      0.83      0.78      7832


Matriz de Confusion con 5 vecinos:
 [[  39 1151]
 [ 152 6490]]


In [ ]:
# Creamoos el clasificador de regresion logistica
knn10 = KNeighborsClassifier(n_neighbors = 10)
# Entrenamos el clasificador
knn10.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn10.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 0.8565224795640327


In [ ]:
# Realizar una prediccion con los datos de prueba
y_pred = knn10.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 10 vecinos: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'Matriz de Confusion con 10 vecinos:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 10 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.20      0.01      0.03      1190
      Pagado       0.85      0.99      0.91      6642

    accuracy                           0.84      7832
   macro avg       0.53      0.50      0.47      7832
weighted avg       0.75      0.84      0.78      7832

Matriz de Confusion con 10 vecinos:
 [[  17 1173]
 [  66 6576]]


In [ ]:
from sklearn.inspection import permutation_importance
result = permutation_importance(knn10, X_test, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame({
"Variable": X.columns,
"Importancia Media": result.importances_mean,
"Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

                      Variable  Importancia Media  Desviación
2                   annual_inc           0.001834    0.001125
0                  funded_amnt           0.001536    0.001122
4                   revol_util           0.000975    0.000369
3                          dti           0.000068    0.000177
18             purpose_medical           0.000000    0.000000
5         pub_rec_bankruptcies           0.000000    0.000000
6                      grade_B           0.000000    0.000000
7                      grade_C           0.000000    0.000000
8                      grade_D           0.000000    0.000000
9                      grade_E           0.000000    0.000000
10                     grade_F           0.000000    0.000000
11                     grade_G           0.000000    0.000000
12         purpose_credit_card           0.000000    0.000000
13  purpose_debt_consolidation           0.000000    0.000000
14         purpose_educational           0.000000    0.000000
15    pu

In [ ]:
# Visualizar importancias con Plotly
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
text_auto=".3f", color="Variable")
fig4.update_layout(width=800, height=600)
fig4.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 1. Seleccionar columnas correctas
X = prestamos_df[['funded_amnt', 'int_rate', 'grade', 'purpose', 'addr_state', 'home_ownership', 'annual_inc', 'dti', 'revol_util', 'pub_rec_bankruptcies']]
y = prestamos_df['loan_status']

# 2. Convertir variables categóricas a números (One-Hot Encoding)
X = pd.get_dummies(X, columns=['grade', 'purpose', 'addr_state', 'home_ownership'], drop_first=True)

# 3. Dividir Datos y limpiar nulos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42, stratify=y)
X_train = X_train.dropna()
y_train = y_train.loc[X_train.index]
X_test = X_test.dropna()
y_test = y_test.loc[X_test.index]

# 4. Normalizar
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 3 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 3 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados y 3 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.25      0.11      0.15      1148
      Pagado       0.86      0.94      0.90      6683

    accuracy                           0.82      7831
   macro avg       0.55      0.53      0.52      7831
weighted avg       0.77      0.82      0.79      7831


Matriz de confusión con datos normalizados y 3 vecinos:
 [[ 123 1025]
 [ 373 6310]] 



In [ ]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 5 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 5 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados y 5 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.26      0.07      0.11      1148
      Pagado       0.86      0.97      0.91      6683

    accuracy                           0.84      7831
   macro avg       0.56      0.52      0.51      7831
weighted avg       0.77      0.84      0.79      7831


Matriz de confusión con datos normalizados y 5 vecinos:
 [[  79 1069]
 [ 222 6461]] 



In [ ]:
# Entrenar KNN
knn_scaled = KNeighborsClassifier(n_neighbors=10)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 10 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 10 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados y 10 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.31      0.05      0.09      1148
      Pagado       0.86      0.98      0.91      6683

    accuracy                           0.84      7831
   macro avg       0.58      0.52      0.50      7831
weighted avg       0.78      0.84      0.79      7831


Matriz de confusión con datos normalizados y 10 vecinos:
 [[  63 1085]
 [ 140 6543]] 

